Source Code/auction/auth.py
from flask import ( 
    Blueprint, flash, render_template, request, url_for, redirect, session
) 
from werkzeug.security import generate_password_hash,check_password_hash
#from .models import User
from .forms import LoginForm,RegisterForm
from .models import User
from flask_login import login_user, login_required, logout_user
from flask_bootstrap import Bootstrap

from . import db


#create a blueprint
bp = Blueprint('auth', __name__)

@bp.route('/register', methods=['GET', 'POST'])
def register():
    register_form_instance = RegisterForm()
    
    # Create user in database
    if register_form_instance.validate_on_submit():
        phone_number = register_form_instance.phone_number.data.replace(" ", "")
        username = register_form_instance.user_name.data
        email = register_form_instance.email_id.data
        pwd = register_form_instance.password.data
        address_line1 = register_form_instance.address_line1.data
        address_line2 = register_form_instance.address_line2.data
        state = register_form_instance.state.data
        zip = register_form_instance.zip.data

        # If user exists already:
        u = User.query.filter_by(user_name=username).first()
        if u:
            flash('This username already exists, please log in', 'info')
            return redirect(url_for('auth.login'))

        u = User.query.filter_by(phone_number=phone_number).first()
        if u:
            flash('Phone number associated with a user already. Please log in', 'info')
            return redirect(url_for('auth.login'))

        u = User.query.filter_by(emailid=email).first()
        if u:
            flash('Email associated with a user already. Please log in', 'info')
            return redirect(url_for('auth.login'))

        # Generate password hash and check against existing hash
        pwd_hash = generate_password_hash(pwd)
        new_user = User(phone_number=phone_number, user_name=username, emailid=email, password_hash=pwd_hash, address_line1=address_line1, address_line2=address_line2, state=state, zip=zip)

        # Add user
        db.session.add(new_user)
        db.session.commit()

        flash("Success! User created. Please log in", "success")
        return redirect(url_for("auth.login"))
    else:
        return render_template('auth/register.html', form=register_form_instance)


# Login user function
@bp.route('/login', methods=['GET', 'POST'])
def login(): #view function
    login_form = LoginForm()
    # Initialise error variable
    error=None
    if(login_form.validate_on_submit()==True):
        user_name = login_form.user_name.data
        password = login_form.password.data

        # Check that user is in database
        u1 = User.query.filter_by(user_name=user_name).first()
        if u1 is None:
            error='Incorrect Username'
        elif not check_password_hash(u1.password_hash, password): # takes the hash and password
            error='Incorrect password'
        if error is None:
            login_user(u1)
            session['user_name'] = user_name
            return redirect(url_for("main.index"))
        else:
            flash(error, 'danger')
    else:
        print(login_form.errors)
    return render_template('auth/login.html', form=login_form, heading='Login')

# Logout user
@bp.route('/logout')
@login_required
def logout():
    logout_user()
    session.pop('user_name')
    flash('Successfully logged out', 'info')
    return redirect(url_for('auth.login'))

Source Code/auction/views.py
from flask import Blueprint, render_template, session, flash
from flask_login import login_required
from .models import User
from datetime import datetime

# this can be removed when the create listing function is moved back to items.py
from .models import Item, Comment, Bid, Watchlist
from .forms import ItemForm, CommentForm
from .items import check_upload_file
from flask import Blueprint, render_template, request, redirect, url_for

bp = Blueprint('main', __name__)


## Index/Home page route
@bp.route('/')
def index():
    items = Item.query.all()
    datetime_now = datetime.now()

    bids = Bid.query.all()
    watchlist = Watchlist.query.all()


    #num bids for each item
    numBidsDict = {}

    for i in range(len(items)):
        numBids = 0
        for bid in bids:
            if (items[i].id == bid.item_id):
                numBids = numBids + 1
        numBidsDict[items[i].id] = numBids

    #num watching for each item
    numWatchDict = {}

    for i in range(len(items)):
        numWatch = 0
        for watch in watchlist:
            if (items[i].id == watch.item_id):
                numWatch = numWatch + 1
        numWatchDict[items[i].id] = numWatch

    top_items = sorted(numBidsDict, key=numBidsDict.get, reverse=True)

    return render_template('landing.html', numWatchDict=numWatchDict, numBidsDict=numBidsDict, items=items,  top_items=top_items, bids=bids, datetime_now=datetime_now)

## For text search 
@bp.route('/search')
def search():
    datetime_now = datetime.now()  
    search_term = request.values.get('search_term')

    if search_term:
        results = Item.query.filter(Item.title.like(f'%{search_term}%')).all()
        
        bids = Bid.query.all()
        watchlist = Watchlist.query.all()

        #num bids for each item
        numBidsDict = {}

        for i in range(len(results)):
            numBids = 0
            for bid in bids:
                if (results[i].id == bid.item_id):
                    numBids = numBids + 1
            numBidsDict[results[i].id] = numBids

        #num watching for each item
        numWatchDict = {}

        for i in range(len(results)):
            numWatch = 0
            for watch in watchlist:
                if (results[i].id == watch.item_id):
                    numWatch = numWatch + 1
            numWatchDict[results[i].id] = numWatch

        return render_template('landing.html', search_term=search_term, results=results, numWatchDict=numWatchDict, numBidsDict=numBidsDict, bids=bids, datetime_now=datetime_now)
    else:
        return redirect(url_for('main.index'))

## Search for games with a particular genre
@bp.route('/genre')
def genre():
    datetime_now = datetime.now()
   
    search_term = request.values.get('search_term')

    if search_term:
        results = Item.query.filter(Item.genre.like(search_term)).all()
        
        bids = Bid.query.all()
        watchlist = Watchlist.query.all()

        #num bids for each item
        numBidsDict = {}

        for i in range(len(results)):
            numBids = 0
            for bid in bids:
                if (results[i].id == bid.item_id):
                    numBids = numBids + 1
            numBidsDict[results[i].id] = numBids

        #num watching for each item
        numWatchDict = {}

        for i in range(len(results)):
            numWatch = 0
            for watch in watchlist:
                if (results[i].id == watch.item_id):
                    numWatch = numWatch + 1
            numWatchDict[results[i].id] = numWatch

        return render_template('landing.html', search_term=search_term, results=results, numWatchDict=numWatchDict, numBidsDict=numBidsDict, bids=bids, datetime_now=datetime_now)
    else:
        return redirect(url_for('main.index'))

## Search for games with a particular platform
@bp.route('/platform')
def platform():
    datetime_now = datetime.now()

    bids = Bid.query.all()
    watchers = Watchlist.query.all()
    
    search_term = request.values.get('search_term')

    if search_term:
        results = Item.query.filter(Item.platform.like(search_term)).all()
        bids = Bid.query.all()
        watchlist = Watchlist.query.all()

        #num bids for each item
        numBidsDict = {}

        for i in range(len(results)):
            numBids = 0
            for bid in bids:
                if (results[i].id == bid.item_id):
                    numBids = numBids + 1
            numBidsDict[results[i].id] = numBids

        #num watching for each item
        numWatchDict = {}

        for i in range(len(results)):
            numWatch = 0
            for watch in watchlist:
                if (results[i].id == watch.item_id):
                    numWatch = numWatch + 1
            numWatchDict[results[i].id] = numWatch

        return render_template('landing.html', search_term=search_term, results=results, numWatchDict=numWatchDict, numBidsDict=numBidsDict, bids=bids, datetime_now=datetime_now)
    else:
        return redirect(url_for('main.index'))

## Search for games with a particular release year
@bp.route('/year')
def year():
    datetime_now = datetime.now()

    bids = Bid.query.all()
    watchers = Watchlist.query.all()
    
    search_term = request.values.get('search_term')

    if search_term:
        results = Item.query.filter(Item.release_year.like(search_term)).all()
        bids = Bid.query.all()
        watchlist = Watchlist.query.all()

        #num bids for each item
        numBidsDict = {}

        for i in range(len(results)):
            numBids = 0
            for bid in bids:
                if (results[i].id == bid.item_id):
                    numBids = numBids + 1
            numBidsDict[results[i].id] = numBids

        #num watching for each item
        numWatchDict = {}

        for i in range(len(results)):
            numWatch = 0
            for watch in watchlist:
                if (results[i].id == watch.item_id):
                    numWatch = numWatch + 1
            numWatchDict[results[i].id] = numWatch

        return render_template('landing.html', search_term=search_term, results=results, numWatchDict=numWatchDict, numBidsDict=numBidsDict, bids=bids, datetime_now=datetime_now)
    else:
        return redirect(url_for('main.index'))

## Watchlist
@bp.route('/watchlist')
@login_required
def watchlist():

    #get user information from db
    user_name = session.get("user_name")
    user = User.query.filter(User.user_name==user_name).first()

    #get watchlist items associated with user
    items = Watchlist.query.filter(Watchlist.user_id==user.id).all()

    # Get bid info
    bids = Bid.query.all()

    #num bids for each item
    numBidsDict = {}
            
    for i in range(len(items)):
        numBids = 0
        for bid in bids:
            if (items[i].item.id == bid.item_id):
                numBids = numBids + 1
        numBidsDict[items[i].id] = numBids 

    return render_template('watchlist.html', items=items, numBidsDict=numBidsDict)

## 404 Error Handler
@bp.app_errorhandler(404)
def error404(error):
    return render_template('errors/404.html'), 404

## 500 Error Handler
@bp.app_errorhandler(500)
def error500(error):
    return render_template('errors/500.html'), 500

@bp.app_errorhandler(Exception)
def catchAllError(error):
    return render_template('errors/catchall.html')

Source Code/auction/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!-- My CSS -->
    <link rel="stylesheet" type="text/css" href="../static/css/mystyle.css">

    <title>Games Auction</title>


</head>

<body>
    <!-- main navbar -->
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-theme-dark">
            <a class="navbar-brand" href="/">
                <b>Games4Auction</b>
            </a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="#">Popular</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Recent</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">For You</a>
                    </li>
                    <form class="form-inline my-2 my-lg-0" action="{{url_for('main.search')}}">
                        <input id="text_input" name="search_term" class="form-control flex-grow-1 my-1 mr-sm-2" placeholder="Search for...">                  
                        <button type="submit" class="btn btn-theme my-2 my-sm-0">Search</button>
                    </form>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('item.create') }}">Create
                            A Listing</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/watchlist">Watchlist</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            My Account
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            {% if current_user.is_authenticated %}
                            <a class="dropdown-item" href="#">My Listings</a>
                            <a class="dropdown-item" href="#">My Bids</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Settings</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{{ url_for('auth.logout') }}">Log Out</a>
                            {% else %}
                            <a class="dropdown-item" href="{{ url_for('auth.login') }}">Login</a>
                            <a class="dropdown-item" href="{{ url_for('auth.register') }}">Register</a>
                            {% endif %}
                        </div>
                    </li>
                </ul>
            </div>
        </nav>
        {% block header %}
        {% endblock %}
    </header>
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="col col-lg-12">
        <div class="alert alert-{{ category }}">{{ message }}</div>
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}
    <main>
        {% block content %}
        {% endblock %}
    </main>

    <footer>
        <div class="footer-text">
            <p>&copy; 2020 Games4Auction</p>
        </div>
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous">
    </script>
</body>

</html>

Source Code/auction/templates/itemdetails.html
{% extends 'base.html' %}

{% import "bootstrap/wtf.html" as wtf %}

{% block content %}

<!-- Page Title -->
<div class="row">
    <!-- full sized column for page title -->
    <div class="col-md-12">
        <h4>Auction details</h4>
    </div>
</div>

<!-- Item Details Section -->
<div class="row section">

    <!-- 1/4 sized column for Item Image -->
    <div class="col-md-3">
        <div>
            <img class="card-img-top" img src="{{ item.image }}" alt="Image for {{ item.name }}" class="img-thumbnail">
        </div>
    </div>

    <!-- 1/2 sized column for Item Text -->
    <div class="col-md-6">
        <div>

            <h5><b>{{ item.title }}</b></h5>

            <p>
                <i>Listed by <b>{{ item.user.user_name }}</b> on <b>{{ item.date_listed.strftime('%d/%m/%Y') }}</b></i>
            </p>

            <p>
                <b>Status:
                    {% if item.is_active == 1 %}
                    <span class="greenText">
                        Active
                    </span>
                    {% else %}
                    <span class="redText">
                        Closed
                    </span>
                    {% endif %}
                </b>
            </p>

            <p>
                <b>Genre: </b>{{ item.genre }}<br>
                <b>Platform: </b>{{ item.platform }}<br>
                <b>Classification: </b>{{ item.classification}}<br>
                <b>Release year: </b>{{ item.release_year }}<br>
                <b>Description: </b> {{ item.description}}
            </p>

        </div>
    </div>

    <!-- 1/4 sized column for Item Bid and Buttons -->
    <div class="text-centre col-md-3">
        <div>

            <h5><b>Current bid:</b></h5>
            <h2><b>
                    <!-- if item is active or inavtive -->
                    {% if item.is_active == 1 %}

                        ${{"%.2f"|format(item.current_bid)}} 

                    {% else %}
                    <span class="greenText">
                        Auction won!
                    </span>
                    {% endif %}
                </b></h2>
        </div>

        <div>
            <p><i>Starting bid was ${{"%.2f"|format(item.starting_bid)}}</i></p>
        </div>


        <!-- Buttons -->

        <div>

            <!-- when current user is the poster -->
            {% if current_user.id == item.user_id %}
                <!-- see bids -->
                <!-- modal trigger button -->
                <div class="centre-btn">
                    <button type="button" class="btn btn-theme" data-toggle="modal" data-target="#bidModal">
                        See Bids
                    </button>
                </div>

                <!-- all bids modal -->
                <!-- <div class="modal fade" id="bidModal" tabindex="-1" aria-labelledby="bidModalLabel" aria-hidden="true"> -->
                <div class="modal fade" id="bidModal" tabindex="-1" aria-labelledby="FormModal" aria-hidden="true">

                    <div class="modal-dialog modal-sm">

                        <!-- Modal content -->
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="bidModalLabel">All Bids</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>

                            <div class="modal-body">
                                <div class="form-group row">
                                    
                                    <table class="table table-bordered">
                                        <!-- Table head -->
                                        <thead>
                                            <tr>
                                                <th>Bid Number</th>
                                                <th>Bid Amount</th>
                                                <th>User Name</th>
                                            </tr>
                                        </thead>

                                        <!-- Table body -->
                                        <tbody>
                                            {% set bid_num = 0 %}

                                            {% for bid in item.bids %}
                                                <tr>
                                                    <td>{{ loop.index }}</td>
                                                    <td>${{"%.2f"|format(bid.bid_amount)}}</td>
                                                    <td>
                                                        {% for user in users %}
                                                            {% if user.id == bid.user_id %}
                                                                {{user.user_name}}
                                                            {% endif %}
                                                        {% endfor %}
                                                    </td>
                                                </tr>
                                            {% endfor %}
                                        </tbody>

                                    </table>
                                </div>

                            </div>

                        </div>
                    </div>
                </div>

                <!-- close/open auction -->
                {% if item.is_active == 1 %}
                <div class="centre-btn">
                    <div class="btn btn-theme">
                        {{wtf.quick_form(form3, "/items/{0}/close".format(item.id))}}
                    </div>
                </div>                
                {% else %}
                <div class="centre-btn">
                    <div class="btn btn-theme">
                        {{wtf.quick_form(form4, "/items/{0}/open".format(item.id))}}
                    </div>
                </div>
                {% endif %}

            <!-- current user is a potential buyer -->
            {% else %}
                <!-- place bid -->
                <!-- modal trigger button -->
                {% if item.is_active == 1 %}
                <div class="centre-btn">
                    <button type="button" class="btn btn-theme" data-toggle="modal" data-target="#bidModal">
                        Place a bid
                    </button>
                </div>
                {% else %}
                <div class="centre-btn">
                    <button type="button" class="btn btn-theme" data-toggle="modal" data-target="#bidModal" disabled>
                        Place a bid
                    </button>
                </div>
                {% endif %}

                <!-- bid modal -->
                <!-- <div class="modal fade" id="bidModal" tabindex="-1" aria-labelledby="bidModalLabel" aria-hidden="true"> -->
                <div class="modal fade" id="bidModal" tabindex="-1" aria-labelledby="FormModal" aria-hidden="true">

                    <div class="modal-dialog modal-sm">

                        <!-- Modal content -->
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="bidModalLabel">Your Bid</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>

                            <div class="modal-body">
                                <div class="form-group row">
                                    {{wtf.quick_form(form1, "/items/{0}/bid".format(item.id))}}
                                </div>

                            </div>
                        </div>
                    </div>
                </div>


                    <!-- watch button -->
                    {% if watching == true %}
                        <div class="centre-btn">
                            <button type="button" class="btn btn-theme" disabled>Watching</button>
                        </div>
                    {% else %}
                        {% if item.is_active == 1 %}
                        <div class="centre-btn">
                            <div class="btn btn-theme">
                                {{wtf.quick_form(form5, "/items/{0}/watch".format(item.id))}}
                            </div>
                        </div>    
                        {% else %}
                            <div class="centre-btn">
                                <button type="button" class="btn btn-theme" disabled>Watch</button>
                            </div>
                        {% endif %}
                    {% endif %}

            {% endif %}

        </div>
    </div>

</div>

<!-- review section-->
<div class="row">
    <!-- full sized column for page title -->
    <div class="bg-theme-light section-centred col-md-10">
        <h6>Reviews</h6>

        <!-- text entry for user -->
        <div class="bg-theme-light section-reviews col-md-8">
            {{wtf.quick_form(form2, "/items/{0}/comment".format(item.id))}}
        </div>

        <!-- divider -->
        <hr />

        <!-- reviews  -->
        {% for comment in item.comments %}
        <div class="bg-theme-light section-reviews col-md-8">

            <!-- header row: username + timestamp -->
            <div class="row">
                <p>
                    <b>{{ comment.user.user_name }}</b>
                </p>
                <div class="timestamp-light">
                    <p>
                        <i>{{ comment.created_at.strftime('%d/%m/%Y %H:%M') }}</i>
                    </p>
                </div>
            </div>
            <!-- second row: review text -->
            <div class="row">
                <p>
                    {{ comment.text }}
                </p>
            </div>
        </div>
        {% endfor %}

    </div>
</div>

{% endblock %}

Source Code/auction/templates/newlisting.html
{% extends 'base.html' %}

{% import "bootstrap/wtf.html" as wtf %}

{% block content %}

<div class="row">
    <div class="col-md-12">
        <h4>Create a listing</h4>
    </div>
</div>
<div class="row">
    <div class="bg-theme-light section-centred col-md-5">
        <div class="col-md-12">
            <div class="bg-theme-light section">
                <h6>Fill in fields below:</h6>
    
                {{wtf.quick_form(form)}}
            </div>
        </div>
    </div>
    

    {% endblock %}

Source Code/auction/templates/watchlist.html
{% extends 'base.html' %}


{% block content %}

<!--{% set items = items|sort(reverse=true, attribute="date_added") %} -->

<div class="row">
    <div class="col-md-3">
        <!-- empty -->
    </div>
    <div class="col-md-6">
        <h4>My Watchlist</h4>
    </div>
    <div class="col-md-3">
        <div class="section-centred">
            <button type="button" class="btn btn-theme">Edit</button>
        </div>
    </div>
</div>


<div class="row">

    <div class="bg-theme-light section-centred col-md-10">

        {% if not items %}
        <h3>Watchlist is empty</h3>
        {% endif %}

        {% for item in items %}
        <!-- item no. 1 -->
        <div class="bg-theme-light section-reviews col-md-11">

            <div class="card">
                <div class="row main-section">

                    <!-- column for image -->
                    <div class="col-md-4 col-sm-4">
                        <img class="card-img-left" src="{{ item.item.image }}" alt="Pokemon Moon for 3DS">
                    </div>

                    <!-- column for auction details -->
                    <div class="col-md-6 col-sm-6">
                        <div class="card-body">
                            <h5><b>{{  item.item.title }}</b></h5>
                            <p>
                                <b>Listed by: </b> {{  item.item.user.user_name }}<br>
                                <b>Date added: </b>{{  item.item.date_listed.strftime('%d/%m/%Y') }}<br>
                            </p>
                            <div class="dropdown-divider"></div>
                            <p>
                                {% if item.item.is_active == 0 %}
                                <b>Status: <span class="redText">Not Active</span></b><br>
                                {% else %}
                                <b>Status: <span class="greenText">Active</span></b><br>
                                {% endif %}
                                <b>Bids: </b>{{  numBidsDict[item.id] }}<br>
                                <b>Highest bid: </b>${{"%.2f"|format(item.item.current_bid)}}<br>
                            </p>
                        </div>
                    </div>

                    <!-- column for view button -->
                    <div class="col-md-2 col-sm-2 section-centred">
                        <a class="btn btn-theme" href="/items/{{ item.item.id }}" role="button">View</a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}

    </div>
</div>

{% endblock %}